# Configuration Settings for Navilock USB GPS device

debug: 1                    # Range 0-4 (0 means no debug statements will print)

save:
  mask: 2048                # Save I/O, Message, INF Message, Nav, Receiver 
                            # Manager, Antenna, and Logging Configuration
  device: 4                 # Save to EEPROM

device: /dev/ttyACM0
frame_id: base_gps
dynamic_model: pedestrian     # MAX Altitude [m]: 9000, MAX Velocity [m/s]: 30, MAX Vertical Velocity [m/s]: 20, Sanity check type: Altitude and Velocity, Max Position Deviation: Small

fix_mode: auto
#dr_limit: 0
enable_ppp: false

rate: 10                     # Measurement rate in Hz
nav_rate: 1                  # in number of measurement cycles

save_on_shutdown: false
clear_bbr: true

usb:
  in: 3
  out: 3

uart1:
  baudrate: 38400           
  in: 32
  out: 32

# TMODE3 Config
# tmode3: 0                   # Survey-In Mode
#sv_in:
#  reset: false              # True: disables and re-enables survey-in (resets)
                            # False: Disables survey-in only if TMODE3 is  
                            # disabled
#  min_dur: 300              # Survey-In Minimum Duration [s]
#  acc_lim: 3.0              # Survey-In Accuracy Limit [m]

# RTCM out config
#rtcm:
#  ids: [5, 87, 77, 230]     # RTCM Messages to configure for Base station
                                   # Enabled: GPS MSM7, GLONASS MSM7, 
                                   # GLONASS CP bias, Stationary RTK ref
                                   # 0xF5 0x05 Stationary RTK reference station
                                   # ARP
                                   # 0xF5 0x4A GPS MSM4
                                   # 0xF5 0x4D GPS MSM7
                                   # 0xF5 0x54 GLONASS MSM4
                                   # 0xF5 0x57 GLONASS MSM7
                                   # 0xF5 0x7C BeiDou MSM4
                                   # 0xF5 0x7F BeiDou MSM7
                                   # 0xF5 0xE6 GLONASS code-phase biases
                                   # 0xF5 0xFE Reference station PVT 
                                   #(u-blox proprietary RTCM Message)
#  rates: [1, 1, 1, 10]      # in number of navigation solutions, must match 
                            # nav_rate, except for 0xE6

dat:
  set: false

# GNSS Config
gnss:
  gps: true
  glonass: true  
  beidou: false
  qzss: false 
  galileo: true
  sbas: true

sbas:
  max: 2

inf: 
  all: true                   # Whether to display all INF messages in console

nmea:
  set: false

# Enable u-blox message publishers
publish:
  all: true
  aid:
    all: false
  nav:
    posecef: false
    clock: false
    pvt: false
    sat: true
    status: false
    svinfo: false
  rxm:
    all: false
  mon:
    all: false
